apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qtech-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/roy35-909/Qtec.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qtech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
